// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'learn-intro', // type: 'doc', id: docs/learn-intro.mdx, label = # đầu tiên của learn-intro.mdx
    {
      type: 'category', // hierarchy - tạo cái danh sách sổ ra
      label: 'At School', // chữ bên sidebar sổ ra
      link: { // tự tạo ra page mục lục hiển thị mọi direct children của category đó
        type: 'generated-index',
        title: '@ HCMUS', // chữ ở trang chính giữa screen
        description: 'Things I\'ve learned at HCMUS 💕',
        // slug: '/not-category/not-label-name', // tạo đường dẫn custom cho page mục lục, default: /category/[categoryName] -> ở đây là /docs/category/at-school
        keywords: ['school', 'hcmus'],
        image: '/img/banner-small.png', // cover or thumbnail image that will be used when displaying the link to your post
      },
      items: [ // bên trong items có thể là 1 type category nữa -> sổ nhiều cấp
        {
          type: 'autogenerated',
          dirName: 'learn/school',
        },
      ],
    },
    {
      type: 'category',
      label: 'At Work',
      link: {
        type: 'generated-index',
        title: 'Learning at workplaces',
        description: 'I grow at work',
        slug: '/lam-viec/met-thay-me',
        keywords: ['work'],
        image: '/img/banner-small.png',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'learn/work',
        },
      ],
    },
    {
      type: 'category',
      label: 'Languages',
      link: {
        type: 'generated-index',
        title: 'Languages that I\'ve learnt',
        description: 'Me speaking',
        keywords: ['language', 'python', 'go'],
        image: '/img/banner-small.png',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'learn/languages',
        },
      ],
    },
    {
      type: 'category',
      label: 'Algorithms',
      link: {
        type: 'generated-index',
        title: 'Algorithms that I know',
        description: 'it\'s hard',
        keywords: ['algorithm', 'math'],
        image: '/img/banner-small.png',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'learn/algorithms',
        },
      ],
    }
  ],
  /**
   * dưới này là custom sidebar để navbar reference tới (getNavBar.js)
   */
  myself: [
    'me-intro', // docs/me-intro
    {
      type: 'autogenerated',
      dirName: 'myself', // docs/myself
    },
    {
      type: 'link',
      label: 'Home',
      href: '/',
    },
    {
      type: 'link',
      label: 'Facebook',
      href: 'https://facebook.com',
    },
  ],
};

module.exports = sidebars;
