// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    /**
     * shortcut for:
     * {
     *   type: 'doc',
     *   id: 'learn-intro' // docs/learn-intro.mdx
     *   label: ''
     * }
     */
    'learn-intro',
    {
      /**
       * type category: create hierarchy of sidebar items - tạo cái danh sách sổ ra
       */
      type: 'category',
      label: 'At School',
      link: {
        /**
         * link: tự tạo ra page mục lục hiển thị mọi direct children của category đó
         */
        type: 'generated-index',
        title: '@ HCMUS',
        description: 'Things I\'ve learned at HCMUS 💕',
        // slug: '/not-category/not-label-name', // tạo đường dẫn custom cho page mục lục, default: /category/[categoryName] -> ở đây là /docs/category/at-school
        keywords: ['hcmus'],
        //image: '/img/docusaurus.png',
      },
      items: [
        /**
         * bên trong items có thể là 1 type category nữa - sổ nhiều cấp
         */
        'learn/school/hcmus/hcmus-intro',
        {
          type: 'category',
          label: 'Freshman',
          link: {
            type: 'generated-index',
            title: 'Freshman',
            description: '(1) freshman year, and someone in their first year is a freshman. You might sometimes hear this shortened to "frosh."',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'learn/school/hcmus/freshman',
            },
          ],
        },
        {
          type: 'category',
          label: 'Sophomore',
          link: {
            type: 'generated-index',
            title: 'Sophomore',
            description: '(2) sophomore year, and someone in their second year is a sophomore. Sometimes sophomore is shortened to “soph.”',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'learn/school/hcmus/sophomore',
            },
          ],
        },
        {
          type: 'category',
          label: 'Junior',
          link: {
            type: 'generated-index',
            title: 'Junior',
            description: '(3) junior year, and someone in their third year is a junior. Junior can be abbreviated as “jr.” in writing.',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'learn/school/hcmus/junior',
            },
          ],
        },
        {
          type: 'category',
          label: 'Senior',
          link: {
            type: 'generated-index',
            title: 'Senior',
            description: '(4) senior year, and someone in their fourth year is a senior. Senior can be abbreviated as “sr.” in writing.',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'learn/school/hcmus/senior',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'At Work',
      link: {
        type: 'generated-index',
        title: 'learn in workplaces',
        description: 'I grow at work',
        slug: '/lam-viec/met-thay-me',
        keywords: ['work'],
      },
      items: [
        {
          type: 'category',
          label: '@ KMS',
          link: {
            type: 'generated-index',
            title: 'Things I learnt at KMS',
            description: 'Things I learnt at KMS (in smaller font)',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'learn/work/kms',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Self',
      link: {
        type: 'generated-index',
        title: 'Self learn',
        description: 'Me teaching myself',
        keywords: ['self'],
      },
      items: [
        {
          type: 'category',
          label: 'GoLang',
          link: {
            type: 'generated-index',
            title: 'Golang',
            description: 'Golang language',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'learn/self/golang',
            },
          ],
        },
      ],
    },
  ],
  /**
   * dưới này là custom sidebar để navbar reference tới (getNavBar.js)
   */
  myself: [
    'me-intro', // docs/me-intro
    {
      /**
       * auto tạo ra:
       * '0-about-me'
       * '1-who-am-i'
       * ...
       */
      type: 'autogenerated',
      dirName: 'myself', // docs/myself
    },
    {
      /**
       * internal link
       */
      type: 'link',
      label: 'Home',
      href: '/',
    },
    {
      /**
       * external link
       */
      type: 'link',
      label: 'Facebook',
      href: 'https://facebook.com',
    },
  ],
};

module.exports = sidebars;
