// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'learn-intro', // type: 'doc', id: docs/learn-intro.mdx, label = # đầu tiên của learn-intro.mdx
    {
      type: 'category',
      label: 'Languages',
      link: {
        type: 'generated-index',
        title: 'Languages that I\'ve learnt',
        description: 'Me speaking',
        keywords: ['language', 'python', 'go'],
        image: '/img/banner-small.png',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'learn/languages',
        },
      ],
    },
    {
      type: 'category',
      label: 'Algorithms',
      link: {
        type: 'generated-index',
        title: 'Algorithms that I know',
        description: 'it\'s hard',
        keywords: ['algorithm', 'math'],
        image: '/img/banner-small.png',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'learn/algorithms',
        },
      ],
    },
    {
      type: 'category',
      label: 'Utilities',
      link: {
        type: 'generated-index',
        title: 'Supportive things',
        description: 'Some knowledge that is supportive for my work',
        keywords: ['util', 'support'],
        image: '/img/banner-small.png',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'learn/utils',
        },
      ],
    }
  ],
  /**
   * dưới này là custom sidebar để navbar reference tới (getNavBar.js)
   */
  myself: [
    'me-intro', // docs/me-intro
    {
      type: 'autogenerated',
      dirName: 'myself', // docs/myself
    },
    {
      type: 'link',
      label: 'Home',
      href: '/',
    },
    {
      type: 'link',
      label: 'Facebook',
      href: 'https://facebook.com',
    },
  ],
};

module.exports = sidebars;
